#!/bin/bash
#
# Title:       multi_config
# Author(s):   btnz
# Description: Downloads required packages and updates local packages
################################################################################
---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:

    - name: Install Required Packages...
      apt:
        name: ['build-essential', 'curl', 'dialog', 'dsniff', 'fortune', 'git', 'golang-go', 'golang', 'htop', 'intel-gpu-tools', 'libffi-dev', 'libssl-dev', 'lshw', 'mc', 'nano', 'netdiscover', 'oscanner', 'p7zip', 'pipenv', 'proxychains4', 'python-apt', 'python-dev', 'python-pip', 'python3-pip', 'smtp-user-enum', 'software-properties-common', 'sudo', 'tnscmd10g', 'unzip', 'wget', 'wkhtmltopdf', 'zip', 'zaproxy']
        update_cache: yes
        cache_valid_time: 3600

    - name: Download libpcap.deb
      get_url:
        url: 'http://archive.ubuntu.com/ubuntu/pool/universe/p/python-libpcap/python-libpcap_0.6.4-1_amd64.deb'
        dest: '/tmp/libpcap.deb'
        force: yes

    - name: Install libpcap.deb
      apt:
        deb: '/tmp/libpcap.deb'

    - name: Update all packages to the latest version
      apt:
        upgrade: full
        autoclean: yes
        autoremove: yes
