#!/bin/bash
#
# Title:       multi_config
# Author(s):   btnz
# Description: Configures Tools
################################################################################
---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:

    - name: Configure AutoRecon
      replace:
        path: '{{ item.path }}'
        regexp: '{{ item.regexp1 }}'
        replace: '{{ item.replace }}'
      with_items:
        - { path: '/opt/autorecon/config/service-scans.toml', regexp1: '-oX', replace: '-oA' }
        - { path: '/opt/autorecon/config/service-scans.toml', regexp1: '\.xml', replace: '' }
        - { path: '/opt/autorecon/config/port-scan-profiles.toml', regexp1: '-oX', replace: '-oA' }
        - { path: '/opt/autorecon/config/port-scan-profiles.toml', regexp1: '\.xml', replace: '' }


    - name: Configure Responder
      replace:
        path: '{{ item.path }}'
        regexp: '{{ item.regexp1 }}'
        replace: '{{ item.replace }}'
      with_items:
        - { path: '/opt/responder/Responder.conf', regexp1: 'files/AccessDenied.html', replace: '/opt/responder/files/AccessDenied.html' }
        - { path: '/opt/responder/Responder.conf', regexp1: 'files/BindShell.exe', replace: '/opt/responder/files/BindShell.exe' }

    - name: Create Symlinks
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dst }}'
        state: link
      with_items:
        - { src: '/opt/autorecon/autorecon.py', dst: '/usr/local/bin/autorecon'}
        - { src: '/opt/responder/Responder.py', dst: '/usr/local/bin/responder'}

    - name: Configure CrackMapExec - Setup pipenv
      become_user: kali
      command: 'pip install --user pipenv'

    - name: Configure CrackMapExec - Install CME in pipenv
      become_user: kali
      command: 'pipenv run python setup.py install'
      args:
        chdir: '/opt/crackmapexec/'
